services:
  - type: web
    name: urduai-pk
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: OPENAI_API_KEY
        sync: false
      - key: SENDFOX_API_TOKEN
        sync: false 